import { GoogleGenerativeAI } from "@google/generative-ai";

const apiKey = "AIzaSyC7HqdgH9Fpi_9Ahlyu5IiEg1moM4bDlvA"; // From .env.local
const genAI = new GoogleGenerativeAI(apiKey);

const model = genAI.getGenerativeModel({
  model: "gemini-flash-latest",
  systemInstruction: "Generate Travel Plan for Location: Las Vegas, for 3 Days for Couple with a Cheap budget,Give me a Hotels options list with HotelName, Hotel address, Price, hotel image url, geo coordinates, rating, descriptions and suggest itinerary with placeName, Place Details, Place Image Url, Geo Coordinates, ticket Pricing, Time t travel each of the location for 3 days with each day plan with best time to visit in JSON format.",
});

const generationConfig = {
  temperature: 1,
  topP: 0.95,
  topK: 40,
  maxOutputTokens: 8192,
  responseMimeType: "application/json",
};

const chatSession = model.startChat({
  generationConfig,
  history: [],
});

async function run() {
  const FINAL_PROMPT = "Generate Travel Plan for Location : Las Vegas, for 3 Days for 2 People with a Cheap budget, give me Hotels options list with HotelName, Hotel address, Price, hotel image url, geo coordinates, rating, descriptions and suggest itinerary with placeName, Place Details, Place Image Url, Geo Coordinates, ticket Pricing, Time travel each of the location for 3 days with each day plan with best time to visit in JSON format."
  try {
    const result = await chatSession.sendMessage(FINAL_PROMPT);
    const text = result.response.text();
    JSON.parse(text);
    console.log("SUCCESS! JSON generated by gemini-2.0-flash.");
  } catch (e) {
    console.error("ERROR", e);
  }
}
run();
